import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-tint": "#bc0b3b",
        "on-primary-fixed-variant": "#92002a",
        "on-background": "#111c2d",
        "surface-dim": "#cfdaf2",
        "surface-container-high": "#dee8ff",
        error: "#ba1a1a",
        "secondary-fixed": "#ffe083",
        background: "#f9f9ff",
        "surface-container-highest": "#d8e3fb",
        "inverse-on-surface": "#ecf1ff",
        "inverse-surface": "#263143",
        "sky-blue-bg": "#E0F2FE",
        "surface-container": "#e7eeff",
        "primary-container": "#dc2c4f",
        "tertiary-fixed-dim": "#d5c867",
        "on-secondary-fixed": "#231b00",
        "on-tertiary-fixed-variant": "#4f4800",
        "on-primary-fixed": "#40000d",
        outline: "#8f6f71",
        "on-error": "#ffffff",
        "on-surface-variant": "#5b4041",
        "on-secondary-container": "#6f5900",
        "success-green": "#22C55E",
        "on-tertiary-container": "#474000",
        "primary-fixed": "#ffdadb",
        "on-surface": "#111c2d",
        "inverse-primary": "#ffb2b7",
        "secondary-fixed-dim": "#eec200",
        "on-error-container": "#93000a",
        "surface-bright": "#f9f9ff",
        primary: "#b90538",
        surface: "#f9f9ff",
        "on-primary-container": "#fffbff",
        "surface-variant": "#d8e3fb",
        "tertiary-container": "#b9ad4f",
        "on-secondary-fixed-variant": "#574500",
        "outline-variant": "#e3bdbf",
        tertiary: "#695f02",
        "secondary-container": "#fed01b",
        secondary: "#735c00",
        "error-container": "#ffdad6",
        "surface-container-low": "#f0f3ff",
        "surface-container-lowest": "#ffffff",
        "ink-navy": "#0F172A",
        "primary-fixed-dim": "#ffb2b7",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#f2e580",
        "on-tertiary-fixed": "#201c00",
        "soft-mint-green": "#a7f3d0",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "stack-md": "24px",
        "stack-lg": "48px",
        gutter: "24px",
        "stack-sm": "12px",
        base: "8px",
        "container-margin-mobile": "20px",
        "container-margin-desktop": "40px",
      },
      fontFamily: {
        sans: ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        display: ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "body-md": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["22px", { lineHeight: "28px", fontWeight: "700" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "display-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.03em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "label-lg": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "600" }],
      },
      boxShadow: {
        neo: "4px 4px 0px 0px rgba(15,23,42,1)",
        "neo-heavy": "8px 8px 0px 0px rgba(15,23,42,1)",
        "neo-sm": "2px 2px 0px 0px rgba(15,23,42,1)",
        card: "0 2px 8px rgba(0,0,0,0.08)",
        glow: "0 4px 16px rgba(0,93,167,0.3)",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-12px)" },
        },
      },
      animation: {
        float: "float 3s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};

export default config;
