import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#a4c9ff",
        "surface-dim": "#d8dadd",
        "surface-container": "#eceef1",
        "on-background": "#191c1e",
        "on-tertiary-fixed-variant": "#852300",
        "on-secondary-fixed": "#261a00",
        "secondary-fixed": "#ffdf9e",
        "surface-container-highest": "#e0e3e6",
        "secondary-container": "#fdc003",
        "primary": "#005da7",
        "on-surface-variant": "#414751",
        "on-primary-fixed": "#001c39",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#004883",
        "secondary": "#785900",
        "on-surface": "#191c1e",
        "outline-variant": "#c1c7d3",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e6e8eb",
        "surface": "#f7f9fc",
        "on-primary-container": "#fdfcff",
        "primary-container": "#2976c7",
        "inverse-surface": "#2d3133",
        "primary-fixed": "#d4e3ff",
        "surface-container-low": "#f2f4f7",
        "surface-bright": "#f7f9fc",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "outline": "#717783",
        "inverse-on-surface": "#eff1f4",
        "on-secondary-fixed-variant": "#5b4300",
        "inverse-primary": "#a4c9ff",
        "tertiary-fixed-dim": "#ffb59f",
        "tertiary-fixed": "#ffdbd0",
        "tertiary-container": "#ca4a20",
        "secondary-fixed-dim": "#fabd00",
        "tertiary": "#a83206",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#3a0a00",
        "surface-variant": "#e0e3e6",
        "on-tertiary-container": "#fffbff",
        "on-error-container": "#93000a",
        "background": "#f7f9fc",
        "surface-tint": "#0060ac",
        "on-secondary-container": "#6c5000",
        "error-container": "#ffdad6",
        "ink-navy": "#0F172A",
        "success-green": "#22C55E",
        "sky-blue-bg": "#E0F2FE",
        "soft-mint-green": "#a7f3d0",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "inline-md": "12px",
        "inline-sm": "8px",
        "inline-xs": "4px",
        "section-padding": "24px",
        "container-margin": "20px",
        "card-gap": "16px",
        "inline-lg": "16px",
        gutter: "24px",
        "container-margin-mobile": "20px",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans"],
        "label-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "headline-lg-mobile": ["22px", { lineHeight: "28px", fontWeight: "700" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "label-lg": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.03em", fontWeight: "700" }],
      },
      boxShadow: {
        neo: "4px 4px 0px 0px rgba(15,23,42,1)",
        "neo-heavy": "8px 8px 0px 0px rgba(15,23,42,1)",
        "neo-sm": "2px 2px 0px 0px rgba(15,23,42,1)",
        card: "0 2px 8px rgba(0,0,0,0.08)",
        glow: "0 4px 16px rgba(0,93,167,0.3)",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-12px)" },
        },
        tanyaPulse: {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(253, 192, 3, 0.6)", transform: "scale(1)" },
          "50%": { boxShadow: "0 0 0 16px rgba(253, 192, 3, 0)", transform: "scale(1.05)" },
        },
      },
      animation: {
        float: "float 3s ease-in-out infinite",
        "pulse-tanya": "tanyaPulse 1.5s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};

export default config;
